### ISSUE TITLE
chaos  --no-log-file info extensions fails for chaostoolkit-addons 0.6.0 up to latest version

### ISSUE THREAD

**Issue by afeblot** [chaostoolkit/chaostoolkit-addons#11]
```sh
/ # python -V
Python 3.9.13

/ # chaos  --no-log-file info core
NAME                VERSION   
CLI                 1.12.0
Core library        1.28.0

/ # chaos  --no-log-file info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION      
                                 
/ # pip install chaostoolkit-addons==0.4.0
Collecting chaostoolkit-addons==0.4.0
  Using cached chaostoolkit_addons-0.4.0-py2.py3-none-any.whl (12 kB)
Installing collected packages: chaostoolkit-addons
Successfully installed chaostoolkit-addons-0.4.0

/ # chaos  --no-log-file info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION                                       
chaostoolkit-addons                     0.4.0     UNKNOWN                       Addons for your Chaos Toolkit experiments


/ # pip install chaostoolkit-addons==0.6.0
Collecting chaostoolkit-addons==0.6.0
  Using cached chaostoolkit_addons-0.6.0-py2.py3-none-any.whl (12 kB)
Installing collected packages: chaostoolkit-addons
  Attempting uninstall: chaostoolkit-addons
    Found existing installation: chaostoolkit-addons 0.4.0
    Uninstalling chaostoolkit-addons-0.4.0:
      Successfully uninstalled chaostoolkit-addons-0.4.0
Successfully installed chaostoolkit-addons-0.6.0

/ # chaos  --no-log-file info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION                                       
Traceback (most recent call last):
  File "/venv/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/chaostoolkit/cli.py", line 502, in info
    fmt.format(
TypeError: unsupported format string passed to NoneType.__format__


/ # pip install chaostoolkit-addons==0.8.6
Collecting chaostoolkit-addons==0.8.6
  Using cached chaostoolkit_addons-0.8.6-py2.py3-none-any.whl (13 kB)
Installing collected packages: chaostoolkit-addons
  Attempting uninstall: chaostoolkit-addons
    Found existing installation: chaostoolkit-addons 0.6.0
    Uninstalling chaostoolkit-addons-0.6.0:
      Successfully uninstalled chaostoolkit-addons-0.6.0
Successfully installed chaostoolkit-addons-0.8.6

/ # chaos  --no-log-file info extensions
NAME                                    VERSION   LICENSE                       DESCRIPTION                                       
Traceback (most recent call last):
  File "/venv/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/chaostoolkit/cli.py", line 502, in info
    fmt.format(
TypeError: unsupported format string passed to NoneType.__format__
/ # 

``

**Comment by Lawouach** [comment]
Hello @afeblot 

Sorry for the long delay. Thanks for the heads up. I'll look into it :)
